/* Data policy: only include values that are published by the manufacturer or explicitly mark unavailable. */
const PRODUCTS = window.ARG_PRODUCTS;

const $=id=>document.getElementById(id);let selected=new Set();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fields=[["Price (UK)", "priceText"],["Weight","weight"],["Display technology","display"],["Resolution","resolution"],["Field of view","fov"],["Refresh rate","refresh"],["Brightness","brightness"],["Tracking","tracking"],["Power / battery","power"],["Camera","camera"],["Audio","audio"],["Compatibility","compatibility"],["Prescription support","prescription"]];
function populateBrands(){const brands=[...new Set(PRODUCTS.map(p=>p.brand))].sort();$("brand-filter").innerHTML='<option value="all">All manufacturers</option>'+brands.map(b=>'<option value="'+esc(b)+'">'+esc(b)+'</option>').join("");}
function render(){const q=$("product-search").value.toLowerCase(),cat=$("category-filter").value,brand=$("brand-filter").value,sort=$("sort-filter").value;let list=PRODUCTS.filter(p=>(cat==="all"||p.category===cat)&&(brand==="all"||p.brand===brand)&&[p.name,p.brand,p.summary,p.display,p.tracking,p.category].join(" ").toLowerCase().includes(q));list.sort((a,b)=>sort==="price-low"?(a.price??Infinity)-(b.price??Infinity):sort==="price-high"?(b.price??-1)-(a.price??-1):sort==="weight"?parseFloat(a.weight)-parseFloat(b.weight):sort==="newest"?b.year-a.year:a.brand.localeCompare(b.brand));$("catalogue-count").textContent=list.length+" of "+PRODUCTS.length+" products";$("selected-count").textContent=selected.size+" selected";$("compare-selected").disabled=selected.size<2;$("no-results").hidden=list.length>0;$("product-grid").innerHTML=list.map(p=>'<article class="product-card '+(selected.has(p.id)?"selected":"")+'"><div class="product-card-top"><div><span class="product-category">'+esc(({display:"Display glasses",ai:"AI smart glasses",spatial:"Spatial / true AR",enterprise:"Enterprise AR"})[p.category])+'</span><h3>'+esc(p.name)+'</h3><div class="product-brand">'+esc(p.brand)+' · '+p.year+'</div></div><div class="product-price">'+esc(p.priceText)+'</div></div><div class="product-card-body"><p class="product-summary">'+esc(p.summary)+'</p><div class="quick-specs"><div class="quick-spec"><b>'+esc(p.resolution)+'</b><span>Resolution</span></div><div class="quick-spec"><b>'+esc(p.fov)+'</b><span>Field of view</span></div><div class="quick-spec"><b>'+esc(p.weight)+'</b><span>Weight</span></div><div class="quick-spec"><b>'+esc(p.tracking)+'</b><span>Tracking</span></div></div></div><div class="product-card-actions"><label><input type="checkbox" data-select="'+p.id+'" '+(selected.has(p.id)?"checked":"")+' '+(!selected.has(p.id)&&selected.size>=3?"disabled":"")+'> Add to compare</label><a href="'+esc(p.source)+'" target="_blank" rel="noopener noreferrer">Manufacturer source ↗</a></div></article>').join("");}
function renderComparison(){const products=PRODUCTS.filter(p=>selected.has(p.id));if(products.length<2){$("comparison").hidden=true;return;}$("comparison").hidden=false;$("comparison-table-wrap").innerHTML='<table class="comparison-table"><thead><tr><th>Specification</th>'+products.map(p=>'<th>'+esc(p.brand)+'<br>'+esc(p.name)+'<br><a href="'+esc(p.source)+'" target="_blank" rel="noopener">Manufacturer ↗</a></th>').join("")+'</tr></thead><tbody>'+fields.map(([label,key])=>'<tr><th>'+esc(label)+'</th>'+products.map(p=>'<td>'+esc(p[key]||"Not disclosed")+'</td>').join("")+'</tr>').join("")+'<tr><th>Overview</th>'+products.map(p=>'<td>'+esc(p.summary)+'</td>').join("")+'</tr></tbody></table>';}
document.addEventListener("change",e=>{if(e.target.matches("[data-select]")){const id=e.target.dataset.select;if(e.target.checked){if(selected.size<3)selected.add(id);}else selected.delete(id);render();}if(["category-filter","brand-filter","sort-filter"].includes(e.target.id))render();});
["product-search"].forEach(id=>$(id).addEventListener("input",render));
$("compare-selected").addEventListener("click",()=>{renderComparison();$("comparison").scrollIntoView({behavior:"smooth"});});
$("clear-comparison").addEventListener("click",()=>{selected.clear();$("comparison").hidden=true;render();});
populateBrands();render();
