const DB_PRODUCTS=[
{id:"xreal-one-pro",name:"XREAL One Pro",brand:"XREAL",cat:"Display glasses",year:2025,price:"£579 UK direct-store listing",weight:"87 g",display:"Sony 0.55-inch micro-OLED",resolution:"1920 × 1080 / eye",fov:"57°",refresh:"Up to 120 Hz",brightness:"Up to 700 nits perceived",tracking:"3DoF / X1 spatial processing",power:"Wired USB-C",camera:"No",audio:"Bose-tuned audio",compat:"USB-C DP Alt Mode; support varies",rx:"Prescription inserts",source:"https://www.xreal.com/uk/"},
{id:"xreal-one",name:"XREAL One",brand:"XREAL",cat:"Display glasses",year:2024,price:"From £349; store price varies",weight:"84 g",display:"Sony micro-OLED",resolution:"1920 × 1080 / eye",fov:"50°",refresh:"Up to 120 Hz",brightness:"Up to 600 nits",tracking:"3DoF / X1 chip",power:"Wired USB-C",camera:"No",audio:"Integrated speakers",compat:"USB-C DP Alt Mode",rx:"Prescription inserts",source:"https://uk.shop.xreal.com/"},
{id:"viture-beast",name:"VITURE Beast",brand:"VITURE",cat:"Display glasses",year:2025,price:"Check UK store",weight:"88 g Regular / 90 g Large",display:"Sony Micro-OLED",resolution:"Up to 1920 × 1200 / eye",fov:"58°",refresh:"Up to 120 Hz",brightness:"Up to 1,250 nits perceived",tracking:"VisionPair 3DoF",power:"Wired USB-C",camera:"Integrated RGB camera",audio:"HARMAN audio",compat:"USB-C DP Alt Mode; adapters",rx:"Prescription options",source:"https://www.viture.com/academy/xr-glasses/the-beast"},
{id:"viture-pro-xr",name:"VITURE Pro XR",brand:"VITURE",cat:"Display glasses",year:2024,price:"Check UK store",weight:"78 g without cable",display:"Sony micro-OLED",resolution:"1920 × 1080 / eye",fov:"46°",refresh:"Up to 120 Hz",brightness:"Up to 1,000 nits",tracking:"3DoF with compatible accessory/software",power:"Wired USB-C",camera:"No",audio:"HARMAN audio",compat:"USB-C DP Alt Mode",rx:"Diopter / prescription options",source:"https://www.viture.com/"},
{id:"rayneo-air4pro",name:"RayNeo Air 4 Pro",brand:"RayNeo",cat:"Display glasses",year:2026,price:"Check UK store",weight:"76 g",display:"0.6-inch SeeYa Micro-OLED; HDR10",resolution:"1920 × 1080 / eye",fov:"46°",refresh:"Up to 120 Hz",brightness:"Up to 1,200 nits",tracking:"No native spatial tracking stated",power:"Wired USB-C",camera:"No",audio:"B&O-tuned audio",compat:"USB-C DP Alt Mode",rx:"Prescription frame available",source:"https://uk.rayneo.com/"},
{id:"rayneo-gtmax",name:"RayNeo GT Max",brand:"RayNeo",cat:"Display glasses",year:2026,price:"£369 listed UK direct",weight:"76 g",display:"Micro-OLED",resolution:"1920 × 1080 / eye",fov:"59°",refresh:"Up to 120 Hz",brightness:"Not stated",tracking:"Native 3DoF",power:"Wired USB-C",camera:"No",audio:"Open-ear audio",compat:"USB-C DP Alt Mode",rx:"Prescription options",source:"https://uk.rayneo.com/"},
{id:"rokid-max2",name:"Rokid Max 2",brand:"Rokid",cat:"Display glasses",year:2025,price:"Check regional store",weight:"75 g",display:"OLED",resolution:"1920 × 1080; up to 1920 × 1200 in supported modes",fov:"50°",refresh:"60–120 Hz mode dependent",brightness:"Up to 600 nits",tracking:"3DoF via compatible accessory",power:"Wired USB-C",camera:"No",audio:"Integrated speakers",compat:"USB-C DP Alt Mode",rx:"Diopter / inserts",source:"https://global.rokid.com/collections/rokid-ar-glasses-series"},
{id:"meta-display",name:"Meta Ray-Ban Display",brand:"Meta / Ray-Ban",cat:"AI smart glasses",year:2026,price:"£749 UK listed",weight:"Varies by frame",display:"Single-lens full-colour integrated display",resolution:"600 × 600 px",fov:"Not published",refresh:"Not published",brightness:"Not published",tracking:"Wristband EMG; not spatial AR",power:"Up to 6 hours listed",camera:"12 MP ultra-wide; 3K/30 video",audio:"2 open-ear speakers; 6-mic array",compat:"iOS / Android requirements apply",rx:"Lens options vary",source:"https://www.ray-ban.com/uk/"},
{id:"rayban-gen3",name:"Ray-Ban Meta (Gen 3)",brand:"Meta / Ray-Ban",cat:"AI smart glasses",year:2026,price:"Check official store",weight:"Varies by frame",display:"No display",resolution:"—",fov:"—",refresh:"—",brightness:"—",tracking:"No spatial tracking",power:"Up to 9 hours claimed; use dependent",camera:"Camera-equipped; model dependent",audio:"Open-ear speakers / multi-mic",compat:"Meta AI app; iOS / Android",rx:"Selected prescription options",source:"https://www.meta.com/"},
{id:"even-g2",name:"Even Realities G2",brand:"Even Realities",cat:"AI smart glasses",year:2025,price:"Check official store",weight:"Approx. 36 g",display:"Binocular green MicroLED waveguide",resolution:"640 × 350",fov:"27.5°",refresh:"60 Hz",brightness:"Up to 1,200 nits",tracking:"No full 6DoF mapping claimed",power:"Up to 2 days typical-use claim",camera:"No camera",audio:"No conventional speakers",compat:"iOS / Android companion app",rx:"Prescription configurations",source:"https://www.evenrealities.com/"},
{id:"rayneo-x3pro",name:"RayNeo X3 Pro",brand:"RayNeo",cat:"Spatial / true AR",year:2025,price:"Around £1,169 UK retail; confirm",weight:"76 g",display:"Dual-eye full-colour MicroLED waveguide",resolution:"640 × 480",fov:"30°",refresh:"Not stated",brightness:"3,500 nits average / 6,000 peak",tracking:"6DoF / SLAM features",power:"245 mAh; runtime varies",camera:"Camera + computer vision sensors",audio:"Open-ear speakers",compat:"Android-based RayNeo AIOS",rx:"Prescription inserts",source:"https://www.rayneo.com/"},
{id:"snap-specs",name:"Snap Specs (2026)",brand:"Snap",cat:"Spatial / true AR",year:2026,price:"US$2,195 announced; UK to confirm",weight:"Not disclosed",display:"See-through AR display; custom optics",resolution:"Not disclosed",fov:"51°",refresh:"Not disclosed",brightness:"Not disclosed",tracking:"Hand tracking + spatial computing",power:"Up to 4 hours announced",camera:"Light / infrared sensing cameras",audio:"Integrated audio",compat:"Snap OS / developer ecosystem",rx:"Prescription inserts announced",source:"https://www.spectacles.com/"},
{id:"vuzix-z100",name:"Vuzix Z100",brand:"Vuzix",cat:"Enterprise AR",year:2024,price:"Business / channel pricing",weight:"38 g",display:"Monocular waveguide",resolution:"640 × 480",fov:"Not stated",refresh:"Not stated",brightness:"Not stated",tracking:"Not consumer 6DoF spatial",power:"Up to 48 hours typical-use claim",camera:"No integrated camera",audio:"No integrated speaker",compat:"iOS / Android companion SDK",rx:"Configuration dependent",source:"https://www.vuzix.com/"},
{id:"realwear-520",name:"RealWear Navigator 520",brand:"RealWear",cat:"Enterprise AR",year:2023,price:"Business / channel pricing",weight:"274 g",display:"Monocular see-through",resolution:"854 × 480",fov:"20°",refresh:"Not stated",brightness:"Not stated",tracking:"Head tracking; not consumer spatial AR",power:"Hot-swappable battery",camera:"48 MP",audio:"Noise-cancelling mic + speaker",compat:"Android-based enterprise platform",rx:"Safety-eyewear configuration",source:"https://www.realwear.com/"},
{id:"magic-leap2",name:"Magic Leap 2",brand:"Magic Leap",cat:"Enterprise AR",year:2022,price:"Enterprise pricing / availability varies",weight:"260 g headset",display:"Optical see-through waveguide",resolution:"1440 × 1760 / eye",fov:"70° diagonal",refresh:"Up to 120 Hz",brightness:"Up to 2,000 nits system rating",tracking:"6DoF spatial tracking",power:"External compute pack",camera:"Tracking / depth sensors",audio:"Spatial audio",compat:"Magic Leap OS",rx:"Prescription inserts",source:"https://www.magicleap.com/"}
];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fields=["name","cat","year","price","weight","display","resolution","fov","refresh","brightness","tracking","power","camera","audio","compat","rx"];
const labels=["Product","Category","Year","UK price","Weight","Display","Resolution","FOV","Refresh","Brightness","Tracking","Power / battery","Camera","Audio","Compatibility","Prescription"];
function render(){
 const q=document.getElementById("db-search").value.toLowerCase(), cat=document.getElementById("db-category").value, brand=document.getElementById("db-brand").value, sort=document.getElementById("db-sort").value;
 let a=DB_PRODUCTS.filter(p=>(cat==="all"||p.cat===cat)&&(brand==="all"||p.brand===brand)&&JSON.stringify(p).toLowerCase().includes(q));
 a.sort((x,y)=>sort==="year"?y.year-x.year:sort==="weight"?(parseFloat(x.weight)||999)-(parseFloat(y.weight)||999):x.name.localeCompare(y.name));
 document.getElementById("db-count").textContent=a.length+" of "+DB_PRODUCTS.length+" products in the current reference set";
 document.getElementById("db-body").innerHTML=a.map(p=>"<tr><td><strong>"+esc(p.name)+"</strong><br><a href='"+esc(p.source)+"' target='_blank' rel='noopener noreferrer'>Manufacturer source ↗</a></td>"+fields.slice(1).map(k=>"<td>"+(k==="cat"?"<span class='db-tag'>"+esc(p[k])+"</span>":esc(p[k]||"Not published"))+"</td>").join("")+"</tr>").join("");
}
[...new Set(DB_PRODUCTS.map(p=>p.brand))].sort().forEach(b=>document.getElementById("db-brand").insertAdjacentHTML("beforeend","<option>"+esc(b)+"</option>"));
["db-search","db-category","db-brand","db-sort"].forEach(id=>document.getElementById(id).addEventListener(id==="db-search"?"input":"change",render));
render();